### ISSUE TITLE
Writing to chip select pin before setting the pin mode to output

### ISSUE THREAD

**Issue by LouisB-CA** [pololu/high-power-stepper-driver-arduino#1]
Two lines of code seem to be in the wrong order in the definition of class DRV8711SPI in file HighPowerStepperDriver.h (lines 46-51)

```
void setChipSelectPin(uint8_t pin)
  {
    csPin = pin;
    digitalWrite(csPin, LOW);
    pinMode(csPin, OUTPUT);
  }
```

The call to `pinMode` should happen before attempting to write to the pin.

**Comment by kevin-pololu** [comment]
This is intentional; by setting the output state before actually making the pin an output, we ensure the pin does not drive high briefly after it is set to an output but before `digitalWrite(..., LOW)` has been called. Doing this works well on an AVR-based Arduinos, but we might revisit this decision if it causes problems with other platforms.
