### ISSUE TITLE
Arduino Uno

### ISSUE THREAD

**Issue by jayronron** [pololu/high-power-stepper-driver-arduino#2]
I am currently using an Arduino Uno and an ample power supply with my motor driver and I am getting appropriate voltage on all input wires to the motor driver but I am getting no output what so ever. I have copy and pasted you example code from the SPI example only changing the lines listed below:

  sd.setCurrentMilliamps36v4(4200);

  sd.setStepMode(HPSDStepMode::MicroStep256);

Any idea why I wouldn't be getting any output voltages from the driver?

**Comment by kevin-pololu** [comment]
Could you post this question on [the Pololu forum](https://forum.pololu.com/) along with pictures of your setup and the full code of the modified program you are using?

The GitHub issues are intended to track development of and problems with the library itself, so I am closing this one since it doesn't appear to be a library problem for now (we can reopen it if that changes).

Kevin
